variables:
  DOCKER_HOST: tcp://thedockerhost:2375/
  DOCKER_DRIVER: overlay2

image:
  name: docker/compose:latest

services:
 - name: docker:dind
   alias: thedockerhost

setup:
  stage: .pre
  script:
    - echo $DOCKER_PASSWORD | docker login index.docker.io --username diazrock --password-stdin
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'  # Don't run on main

build-job:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'  # Don't run on main

setup-environment:
  stage: test
  script:
    - echo "Running docker compose"
    - docker-compose up -d --build
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'  # Don't run on main

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - sleep 20
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'  # Don't run on main

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'  # Don't run on main
