version: '3'
services:
  api_gateway:
    build: ./apps/http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./apps/http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - SERVICE_DOMAIN=api_gateway
    networks:
      - app-network
  users_microservice:
    build: ./apps/users-microservice
    volumes:
      - ./apps/users-microservice/src:/usr/src/app/src
    command: npm run start:dev
    networks:
      - app-network
  payments_microservice:
    build: ./apps/payments-microservice
    volumes:
      - ./apps/payments-microservice/src:/usr/src/app/src
    command: npm run start:dev
    networks:
      - app-network
  nats:
    image: nats
    ports:
      - 4222:4222
    environment:
      - NATS_URL=nats://localhost:4222
    networks:
      - app-network
  mongodb_service:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGODB_DATABASE="authdb"
    networks:
      - app-network
  mysql_db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nestjs_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
    networks:
      - app-network
  auth_service:
    build: ./apps/auth
    volumes:
      - ./apps/auth/src:/usr/src/app/src
    command: npm run start:debug
    environment:
      - JWT_SECRET=your_secret_key
      - JWT_EXPIRATION=3600
      - HTTP_PORT=3001
      - TCP_PORT=3002
      - SECRET_KEY_BASE=secret
      - MONGO_URI=mongodb://root:example@mongodb_service:27017
    networks:
      - app-network
    depends_on:
      - 'mongodb_service'
  frontend_app:
    build: ./apps/frontend
    volumes:
    - ./apps/frontend/:/usr/src/app/
    ports:
      - "8080:3000"
    environment:
      - API_BASE_URL=http://api_gateway:3000
    command: npm run start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge