name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker-compose build
          docker-compose push
      
      - name: Build frontend app
        run: |
          docker-compose up frontend_app
          docker-compose exec frontend_app npm run build
          docker cp frontend:/usr/src/app/build .
          docker-compose stop frontend_app

      - name: Check builded folder
        run: | 
          pwd 
          ls -alF

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          branch: main  # adjust if using a different branch for GitHub Pages
          folder: ./build  # adjust to your frontend build output path
