name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Render CLI
      run: |
        curl -L -o render.tar.gz https://github.com/renderinc/render/releases/latest/download/render_linux_amd64.tar.gz
        tar -xzf render.tar.gz
        chmod +x render
        sudo mv render /usr/local/bin/

    - name: Verify Render CLI Installation
      run: render --version

    - name: Login to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: render login --api-key $RENDER_API_KEY

    - name: Deploy services to Render
      run: render deploy --path ./render.yaml
